version: 2
jobs:
  build:
    working_directory: ~/volca-linkdrop-core
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/volca-linkdrop-core/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build the 'dist' folder
          command: npm run build

  test:
    working_directory: ~/volca-linkdrop-core
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/volca-linkdrop-core/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: unit-test
          command:  npm run test:coverage
      - run:
          name: plato
          command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports

  whitesource:
    working_directory: ~/volca-linkdrop-core
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/volca-linkdrop-core/workspace
      - run :
          name: Setup WhiteSource
          command: curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: execute whitesource
          command: |
            cd .whitesource/
            chmod +x wss_agent.sh && ./wss_agent.sh -apiKey $WHITESOURCE_API_KEY -c ./whitesource-fs-agent.config  -project volca-linkdrop-core -f files.list

  publish:
    working_directory: ~/volca-linkdrop-core
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/volca-linkdrop-core/dist
      - run: ls -al
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/volca-linkdrop-core/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            .circleci/announcePublish.sh "Volca-Linkdrop-Core" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - whitesource:
          requires:
            - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                  - master
